import os
import re

IGNORE_DIRS = {'.git', 'venv', '.venv', 'node_modules', '__pycache__', '.next', 'media', 'staticfiles', '.vscode', 'chroma_db'}
IGNORE_EXTS = {'.pyc', '.png', '.jpg', '.jpeg', '.gif', '.svg', '.ico', '.pdf', '.zip', '.tar.gz', '.sqlite3', '.log'}

def parse_symbols(filepath):
    symbols = []
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line.startswith('class ') or line.startswith('def '):
                    match = re.search(r'^(class|def)\s+([a-zA-Z0-9_]+)', line)
                    if match:
                        symbols.append(f"  {match.group(1)} {match.group(2)}")
                elif line.startswith('export const ') or line.startswith('export function ') or line.startswith('export default '):
                    symbols.append(f"  {line.split('=')[0].split('(')[0].split('{')[0].strip()}")
    except Exception:
        pass # Ignore binary files or decode errors
    return symbols

def main():
    root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    output_file = os.path.join(root_dir, 'repomap.txt')
    
    with open(output_file, 'w', encoding='utf-8') as out:
        out.write("MONTROSE AGENCY PORTAL - REPOSITORY MAP\n")
        out.write("=======================================\n")
        out.write("This file is automatically generated. Use it as an index to locate files and functions.\n\n")
        
        for root, dirs, files in os.walk(root_dir):
            # Prune ignored directories
            dirs[:] = [d for d in sorted(dirs) if d not in IGNORE_DIRS]
            
            # Print file paths
            rel_dir = os.path.relpath(root, root_dir)
            if rel_dir == '.':
                rel_dir = ''
            
            for file in sorted(files):
                if file == 'repomap.txt' or any(file.endswith(ext) for ext in IGNORE_EXTS):
                    continue
                
                filepath = os.path.join(root, file)
                rel_file = os.path.join(rel_dir, file).replace('\\', '/')
                if rel_file.startswith('/'): rel_file = rel_file[1:]
                
                out.write(f"\n📄 {rel_file}\n")
                
                # Extract symbols
                symbols = parse_symbols(filepath)
                if symbols:
                    out.write("\n".join(symbols) + "\n")
                    
    print(f"✅ Successfully wrote repomap.txt to {output_file}")

if __name__ == '__main__':
    main()
