"""
File Operations — Applies structured file changes from Implementer to disk.
Handles CREATE, MODIFY, DELETE with backup safety.
"""

import shutil
from datetime import datetime, timezone
from pathlib import Path
from src.config import MONTRROASE_ROOT


class FileApplicator:
    """
    Safely applies file operations generated by the Implementer agent.
    Creates backups before modifying existing files.
    """

    def __init__(self, dry_run: bool = False):
        """
        Args:
            dry_run: If True, reports what would be done without touching disk.
        """
        self.dry_run = dry_run
        self.applied: list[dict] = []  # Track what was applied (for rollback)

    def apply_all(self, file_operations: list[dict]) -> list[dict]:
        """
        Apply a list of file operations from the Implementer's JSON output.

        Args:
            file_operations: List of dicts with keys: operation, path, content, change_summary

        Returns:
            List of results with 'path', 'operation', 'status', 'error'
        """
        results = []
        for op in file_operations:
            result = self._apply_single(op)
            results.append(result)
        return results

    def _apply_single(self, op: dict) -> dict:
        """Apply a single file operation."""
        operation = op.get("operation", "").upper()
        rel_path = op.get("path", "")
        content = op.get("content", "")

        if not rel_path:
            return {"path": rel_path, "operation": operation, "status": "error",
                    "error": "Empty path"}

        # Resolve the full path
        full_path = self._resolve_path(rel_path)

        try:
            if operation == "CREATE":
                return self._create_file(full_path, rel_path, content)
            elif operation == "MODIFY":
                return self._modify_file(full_path, rel_path, content)
            elif operation == "DELETE":
                return self._delete_file(full_path, rel_path)
            else:
                return {"path": rel_path, "operation": operation, "status": "error",
                        "error": f"Unknown operation: {operation}"}
        except Exception as e:
            return {"path": rel_path, "operation": operation, "status": "error",
                    "error": str(e)}

    def _resolve_path(self, rel_path: str) -> Path:
        """
        Resolve a relative path to an absolute path.
        Paths are relative to Montrroase_website root.
        """
        # Strip leading slashes/backslashes
        clean = rel_path.lstrip("/\\")
        return MONTRROASE_ROOT / clean

    def _create_file(self, full_path: Path, rel_path: str, content: str) -> dict:
        """Create a new file. Warns if it already exists."""
        if full_path.exists():
            # Treat as modify with backup
            return self._modify_file(full_path, rel_path, content, label="CREATE→MODIFY")

        if not self.dry_run:
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content, encoding="utf-8")

        self.applied.append({"op": "CREATE", "path": full_path, "backup": None})
        return {"path": rel_path, "operation": "CREATE", "status": "ok" if not self.dry_run else "dry_run"}

    def _modify_file(self, full_path: Path, rel_path: str, content: str, label: str = "MODIFY") -> dict:
        """Modify an existing file (backs up the original first)."""
        backup_path = None

        if not self.dry_run:
            full_path.parent.mkdir(parents=True, exist_ok=True)

            # Create backup if file exists
            if full_path.exists():
                ts = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
                backup_path = full_path.with_suffix(f".bak.{ts}{full_path.suffix}")
                shutil.copy2(full_path, backup_path)

            full_path.write_text(content, encoding="utf-8")

        self.applied.append({"op": label, "path": full_path, "backup": backup_path})
        return {
            "path": rel_path,
            "operation": label,
            "status": "ok" if not self.dry_run else "dry_run",
            "backup": str(backup_path) if backup_path else None,
        }

    def _delete_file(self, full_path: Path, rel_path: str) -> dict:
        """Delete a file (backs up first)."""
        if not full_path.exists():
            return {"path": rel_path, "operation": "DELETE", "status": "skipped",
                    "error": "File does not exist"}

        backup_path = None
        if not self.dry_run:
            # Backup before delete
            ts = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
            backup_path = full_path.with_suffix(f".deleted.{ts}{full_path.suffix}")
            shutil.copy2(full_path, backup_path)
            full_path.unlink()

        self.applied.append({"op": "DELETE", "path": full_path, "backup": backup_path})
        return {
            "path": rel_path,
            "operation": "DELETE",
            "status": "ok" if not self.dry_run else "dry_run",
            "backup": str(backup_path) if backup_path else None,
        }

    def rollback(self):
        """
        Rollback all applied operations.
        Restores from backups where possible.
        """
        for op in reversed(self.applied):
            try:
                path: Path = op["path"]
                backup: Path | None = op["backup"]
                operation: str = op["op"]

                if operation == "CREATE" and path.exists():
                    path.unlink()
                elif operation in ("MODIFY", "CREATE→MODIFY") and backup and backup.exists():
                    shutil.copy2(backup, path)
                    backup.unlink()
                elif operation == "DELETE" and backup and backup.exists():
                    shutil.copy2(backup, path)
                    backup.unlink()
            except Exception:
                pass  # Best-effort rollback
